# Generated by Django 4.2.4 on 2023-08-29 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_snippet_language_alter_snippet_styles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='styles',
            new_name='style',
        ),
        migrations.AlterField(
            model_name='snippet',
            name='title',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
